# pyproject.toml

[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/foo.py  # exclude a file named foo.py in the root of the project
'''

[tool.validate_imports]
exclude = ["*/migrations/*"]  # Carpetas a excluir

[tool.ruff]
# Only keep the non-deprecated top-level settings
line-length = 88
indent-width = 4
target-version = "py312"
extend-exclude = [
    "*/migrations/*",    # Excluir todas las carpetas de migraciones
    "__pycache__",
    ".git",
    ".ruff_cache",
    "__init__.py",
]
select = [
    "E",
    "F",
    "I",
    "N",
    "D",
    "UP",
    "ANN",
    "B",
    "C",
    "T",
    "Q",
    "RUF",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "F403",
    "I001",
    "TID",
    "NPY",
    "TID252",
]
extend-select = ["I"]  # Enable isort rules

[tool.ruff.lint]
# Moved from top-level to lint section
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "N",    # pep8-naming
    "D",    # pydocstring
    "UP",   # pyupgrade
    "ANN",  # flake8-annotations (type hints)
    "B",    # flake8-bugbear
    "C",    # flake8-comprehensions
    "T",    # flake8-print
    "Q",    # flake8-quotes
    "RUF",  # Ruff-specific rules
    "PLC",  # pylint-convention
    "PLE",  # pylint-error
    "PLR",  # pylint-refactor
    "PLW",  # pylint-warning
    "F403", # Ban 'from module import *'
    "I001", # Import block organization
    "TID",  # flake8-tidy-imports
]
ignore = [
    "D100",  # Missing docstring in public module
    "PLC0414", # Useless import alias
]
unfixable = ["F401"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.isort]
known-first-party = ["app", "accounts"]
force-single-line = true
required-imports = ["from __future__ import annotations"]
combine-as-imports = false
force-wrap-aliases = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
mypy-init-return = false
suppress-none-returning = true
suppress-dummy-args = true

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "D100"]
"utils/logger.py" = ["T201"]
"pre-commit-scripts/validate_imports.py" = ["T201"]
"tests/*" = ["D", "ANN"]
"*/migrations/*" = ["D", "ANN"]
"app/settings.py" = ["D", "ANN"]
"*/urls.py" = ["D"]

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = false
disallow_untyped_decorators = false
no_implicit_optional = false
strict_optional = false
warn_return_any = false
warn_unused_ignores = false
warn_redundant_casts = false
warn_unused_configs = false
