# Generated by Django 5.1.4 on 2024-12-22 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_is_verified_verificationcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="MFAMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("otp", "One-Time Password"),
                            ("email", "Email Verification"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MFA method",
                "verbose_name_plural": "MFA methods",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="has_mfa",
            field=models.BooleanField(
                default=False, help_text="Indicates if user has configured MFA"
            ),
        ),
        migrations.CreateModel(
            name="MFAVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "session_key",
                    models.CharField(
                        help_text="Temporary session key for MFA verification process",
                        max_length=64,
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="accounts.mfamethod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MFA verification",
                "verbose_name_plural": "MFA verifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserMFA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "otp_secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret key for TOTP generation",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "backup_codes",
                    models.JSONField(
                        blank=True, help_text="List of one-time backup codes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_users",
                        to="accounts.mfamethod",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user MFA configuration",
                "verbose_name_plural": "user MFA configurations",
            },
        ),
    ]
