# Generated by Django 5.1.4 on 2024-12-29 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_insert_initial_mfa_methods"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mfaverification",
            options={"ordering": ["-created_at"], "verbose_name": "MFA verification"},
        ),
    ]
