# Generated by Django 5.1.4 on 2025-02-10 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_mfaverification_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="has_password",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="MagicLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("login", "Login"),
                            ("password_set", "Password Set"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magic_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["token", "is_used"], name="accounts_ma_token_339579_idx"
                    ),
                    models.Index(
                        fields=["user", "type", "is_used"],
                        name="accounts_ma_user_id_f1ad2e_idx",
                    ),
                ],
            },
        ),
    ]
